version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules/
    depends_on:
      - cms
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - default
    environment:
      FRONTEND_CMS_HOST: 'http://cms:${CMS_PORT}'

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data/database:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'

  cms:
    container_name: cms
    build:
      context: cms
      dockerfile: Dockerfile
    ports:
      - "${CMS_PORT}:${CMS_PORT}"
    networks:
      - default
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'

      ADMIN_EMAIL: '${CMS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${CMS_ADMIN_PASSWORD}'

      # Make sure to set this in production
      # (see https://docs.CMS.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://CMS.example.com'

networks:
  default:
