version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules/
    depends_on:
      - directus
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - directus

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'

  directus:
    container_name: directus
    build:
      context: ./directus
      dockerfile: Dockerfile
    ports:
      - "${DIRECTUS_PORT}:${DIRECTUS_PORT}"
#    volumes:
#      - ./directus:/directus
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'

      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PASSWORD}'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
