version: 1
directus: 9.18.1
collections:
  - collection: Posts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: Posts
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: draft
    schema:
      comment: null
      name: Posts
      schema: public
fields:
  - collection: Posts
    field: Title
    meta:
      collection: Posts
      conditions: null
      display: null
      display_options: null
      field: Title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: Title
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: Posts
    type: string
  - collection: Posts
    field: id
    meta:
      collection: Posts
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('"Posts_id_seq"'::regclass)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: Posts
    type: integer
  - collection: Posts
    field: status
    meta:
      collection: Posts
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            foreground: '#FFFFFF'
            background: var(--primary)
          - text: $t:draft
            value: draft
            foreground: '#18222F'
            background: '#D3DAE4'
          - text: $t:archived
            value: archived
            foreground: '#FFFFFF'
            background: var(--warning)
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: draft
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: Posts
    type: string
relations: []
