#!/bin/bash
FILE=.env
if test -f "$FILE"; then
    echo "$FILE exists"
else
    echo "$FILE does not exist. Creating from example"
  cp .env.example .env
fi

docker-compose build --no-cache

# TODO: Load the cms/schema.yaml file, maybe upload some dummy starter data